stDemoOne/force-app/main/default/objects/gps_FundingAwardContract__c/gps_FundingAwardContract__c.object-meta.xml
<CustomObject>
    <label>Funding Award Contract</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Award Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

stDemoOne/force-app/main/default/objects/gps_FundingAwardContract__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Funding Award</label>
    <referenceTo>FundingAward</referenceTo>
    <relationshipLabel>Funding Award Contracts</relationshipLabel>
    <relationshipName>Funding_Award_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

stDemoOne/force-app/main/default/classes/gps_CreateContractControllerOnChild.cls
public class gps_CreateContractControllerOnChild {
@AuraEnabled
    public static List<String> getCreatedRecord(String sourceRecordId, Boolean autoDocgen) {
        
        String childId = [SELECT Id FROM gps_FundingAwardContract__c WHERE ParentId__c = :sourceRecordId ORDER BY LastModifiedDate DESC LIMIT 1].Id;
       
        ConnectApi.ContractInputRepresentation objInput = new ConnectApi.ContractInputRepresentation();
        objInput.sourceObjectId = childId;
        objInput.isAutoDocgenRequired = autoDocgen;
        ConnectApi.ContractOutputRepresentation objOutput = ConnectApi.Clm.createContract(objInput);
         List<String> contractData = new List<String>();
        contractData.add(objOutput.data[0]);
         List<Contract> contractName = [SELECT Name FROM Contract WHERE Id =:objOutput.data[0]];
        contractData.add(contractName[0].Name);
        return contractData;
        
    }
}